export const songCatalog = [
  "Too Busy To Be Bae (Francis x)",
  "One More Time (Daft Punk)",
  "Bohemian Rhapsody (Queen)",
  "Blinding Lights (The Weeknd)",
  "Lose Yourself (Eminem)",
  "Shape of You (Ed Sheeran)",
  "Smells Like Teen Spirit (Nirvana)",
  "Rolling in the Deep (Adele)",
  "Get Lucky (Daft Punk)",
  "Bad Guy (Billie Eilish)",
  "Billie Jean (Michael Jackson)",
  "Levitating (Dua Lipa)",
  "Stairway to Heaven (Led Zeppelin)",
  "Savage Love (Jason Derulo)",
  "Old Town Road (Lil Nas X)",
  "Heat Waves (Glass Animals)",
  "Montero (Lil Nas X)",
  "Shallow (Lady Gaga)",
  "Watermelon Sugar (Harry Styles)",
  "drivers license (Olivia Rodrigo)",
  "Good 4 U (Olivia Rodrigo)",
  "Stay (The Kid LAROI)",
  "As It Was (Harry Styles)",
  "Industry Baby (Lil Nas X)",
  "Butter (BTS)",
  "Dynamite (BTS)",
  "Permission to Dance (BTS)",
  "Peaches (Justin Bieber)",
  "Intentions (Justin Bieber)",
  "Circles (Post Malone)",
  "Sunflower (Post Malone)",
  "Rockstar (DaBaby)",
  "SICKO MODE (Travis Scott)",
  "Goosebumps (Travis Scott)",
  "HUMBLE. (Kendrick Lamar)",
  "Alright (Kendrick Lamar)",
  "DNA. (Kendrick Lamar)",
  "The Box (Roddy Ricch)",
  "WAP (Cardi B)",
  "Up (Cardi B)",
  "Super Bass (Nicki Minaj)",
  "Starships (Nicki Minaj)",
  "Anaconda (Nicki Minaj)",
  "Hey Ya! (OutKast)",
  "Ms. Jackson (OutKast)",
  "Hey Look Ma, I Made It (Panic! At The Disco)",
  "High Hopes (Panic! At The Disco)",
  "I Write Sins Not Tragedies (Panic! At The Disco)",
  "Mr. Brightside (The Killers)",
  "Somebody Told Me (The Killers)",
  "Use Somebody (Kings of Leon)",
  "Sex on Fire (Kings of Leon)",
  "Take Me Out (Franz Ferdinand)",
  "Do I Wanna Know? (Arctic Monkeys)",
  "R U Mine? (Arctic Monkeys)",
  "I Bet You Look Good on the Dancefloor (Arctic Monkeys)",
  "The Less I Know The Better (Tame Impala)",
  "Feels Like We Only Go Backwards (Tame Impala)",
  "Elephant (Tame Impala)",
  "Midnight City (M83)",
  "Wait (M83)",
  "Reunion (M83)",
  "Electric Feel (MGMT)",
  "Kids (MGMT)",
  "Time to Pretend (MGMT)",
  "Some Nights (fun.)",
  "We Are Young (fun.)",
  "Carry On (fun.)",
  "Pumped Up Kicks (Foster The People)",
  "Sit Next to Me (Foster The People)",
  "Houdini (Foster The People)",
  "1901 (Phoenix)",
  "Lisztomania (Phoenix)",
  "If I Ever Feel Better (Phoenix)",
  "Somewhere Only We Know (Keane)",
  "Everybody's Changing (Keane)",
  "This Is the Last Time (Keane)",
  "Chasing Cars (Snow Patrol)",
  "Run (Snow Patrol)",
  "Just Say Yes (Snow Patrol)",
  "Viva La Vida (Coldplay)",
  "Yellow (Coldplay)",
  "The Scientist (Coldplay)",
  "Clocks (Coldplay)",
  "Fix You (Coldplay)",
  "Paradise (Coldplay)",
  "Adventure of a Lifetime (Coldplay)",
  "Counting Stars (OneRepublic)",
  "Secrets (OneRepublic)",
  "Apologize (OneRepublic)",
  "Love Runs Out (OneRepublic)",
  "Demons (Imagine Dragons)",
  "Radioactive (Imagine Dragons)",
  "Believer (Imagine Dragons)",
  "Thunder (Imagine Dragons)",
  "Whatever It Takes (Imagine Dragons)",
  "Stressed Out (Twenty One Pilots)",
  "Ride (Twenty One Pilots)",
  "Heathens (Twenty One Pilots)",
  "Blinding Lights (The Weeknd)",
  "Save Your Tears (The Weeknd)",
  "Starboy (The Weeknd)",
  "The Hills (The Weeknd)",
  "I Feel It Coming (The Weeknd)",
  "Can't Feel My Face (The Weeknd)",
  "One Dance (Drake)",
  "Hotline Bling (Drake)",
  "God's Plan (Drake)",
  "Passionfruit (Drake)",
  "Nonstop (Drake)",
  "In My Feelings (Drake)",
  "SICKO MODE (Travis Scott)",
  "goosebumps (Travis Scott)",
  "HIGHEST IN THE ROOM (Travis Scott)",
  "Antidote (Travis Scott)",
  "Butterfly Effect (Travis Scott)",
  "Praise God (Kanye West)",
  "Flashing Lights (Kanye West)",
  "Runaway (Kanye West)",
  "Stronger (Kanye West)",
  "Power (Kanye West)",
  "Ultralight Beam (Kanye West)",
  "Gold Digger (Kanye West)",
  "N95 (Kendrick Lamar)",
  "HUMBLE. (Kendrick Lamar)",
  "Alright (Kendrick Lamar)",
  "Money Trees (Kendrick Lamar)",
  "LOVE. (Kendrick Lamar)",
  "DNA. (Kendrick Lamar)",
  "Swimming Pools (Drank) (Kendrick Lamar)",
  "Family Ties (Baby Keem)",
  "First Class (Jack Harlow)",
  "Industry Baby (Lil Nas X)",
  "Montero (Call Me By Your Name) (Lil Nas X)",
  "Old Town Road (Lil Nas X)",
  "Panini (Lil Nas X)",
  "Sunflower (Post Malone)",
  "Circles (Post Malone)",
  "Wow. (Post Malone)",
  "Congratulations (Post Malone)",
  "Rockstar (Post Malone)",
  "White Iverson (Post Malone)",
  "Stay (The Kid LAROI)",
  "WITHOUT YOU (The Kid LAROI)",
  "Lucid Dreams (Juice WRLD)",
  "All Girls Are The Same (Juice WRLD)",
  "Robbery (Juice WRLD)",
  "Legends (Juice WRLD)",
  "Come & Go (Juice WRLD)",
  "Wishing Well (Juice WRLD)",
  "Sad! (XXXTENTACION)",
  "Moonlight (XXXTENTACION)",
  "Jocelyn Flores (XXXTENTACION)",
  "Look At Me! (XXXTENTACION)",
  "Hope (XXXTENTACION)",
  "Falling Down (Lil Peep)",
  "Awful Things (Lil Peep)",
  "Star Shopping (Lil Peep)",
  "Save That Shit (Lil Peep)",
  "Benz Truck (Lil Peep)",
  "Come Over When You're Sober (Lil Peep)",
  "Lose Yourself (Eminem)",
  "The Real Slim Shady (Eminem)",
  "Mockingbird (Eminem)",
  "Without Me (Eminem)",
  "Love The Way You Lie (Eminem)",
  "Not Afraid (Eminem)",
  "Rap God (Eminem)",
  "Forever (Drake, Kanye West, Lil Wayne, Eminem)",
  "Empire State of Mind (Jay-Z)",
  "N***** In Paris (Jay-Z, Kanye West)",
  "99 Problems (Jay-Z)",
  "Run This Town (Jay-Z, Rihanna, Kanye West)",
  "Holy Grail (Jay-Z, Justin Timberlake)",
  "Otis (Jay-Z, Kanye West)",
  "Still D.R.E. (Dr. Dre, Snoop Dogg)",
  "The Next Episode (Dr. Dre, Snoop Dogg)",
  "Nuthin' But a 'G' Thang (Dr. Dre, Snoop Dogg)",
  "California Love (2Pac, Dr. Dre)",
  "Changes (2Pac)",
  "Hit 'Em Up (2Pac)",
  "Dear Mama (2Pac)",
  "Hail Mary (2Pac)",
  "Juicy (The Notorious B.I.G.)",
  "Big Poppa (The Notorious B.I.G.)",
  "Hypnotize (The Notorious B.I.G.)",
  "Mo Money Mo Problems (The Notorious B.I.G.)",
  "It Was A Good Day (Ice Cube)",
  "Straight Outta Compton (N.W.A.)",
  "No Vaseline (Ice Cube)",
  "Regulate (Warren G, Nate Dogg)",
  "This Is How We Do It (Montell Jordan)",
  "Return of the Mack (Mark Morrison)",
  "Pony (Ginuwine)",
  "No Diggity (Blackstreet, Dr. Dre)",
  "Thong Song (Sisqó)",
  "Yeah! (Usher, Lil Jon, Ludacris)",
  "Confessions Part II (Usher)",
  "Burn (Usher)",
  "My Boo (Usher, Alicia Keys)",
  "Let Me Love You (Mario)",
  "So Sick (Ne-Yo)",
  "Because of You (Ne-Yo)",
  "Irreplaceable (Beyoncé)",
  "Halo (Beyoncé)",
  "Crazy In Love (Beyoncé, Jay-Z)",
  "Single Ladies (Beyoncé)",
  "Drunk in Love (Beyoncé, Jay-Z)",
  "If I Were a Boy (Beyoncé)",
  "Love On Top (Beyoncé)",
  "We Belong Together (Mariah Carey)",
  "Always Be My Baby (Mariah Carey)",
  "Fantasy (Mariah Carey)",
  "Hero (Mariah Carey)",
  "Vision of Love (Mariah Carey)",
  "My All (Mariah Carey)",
  "Bleeding Love (Leona Lewis)",
  "Tattoo (Jordin Sparks)",
  "No Air (Jordin Sparks, Chris Brown)",
  "With You (Chris Brown)",
  "Forever (Chris Brown)",
  "Yeah 3x (Chris Brown)",
  "Beautiful People (Chris Brown, Benny Benassi)",
  "Turn Up The Music (Chris Brown)",
  "Kiss Kiss (Chris Brown, T-Pain)",
  "Loyal (Chris Brown, Lil Wayne, Tyga)",
  "Don’t Wake Me Up (Chris Brown)",
  "Wake Me Up (Avicii, Aloe Blacc)",
  "Hey Brother (Avicii)",
  "Levels (Avicii)",
  "The Nights (Avicii)",
  "Waiting for Love (Avicii)",
  "I Could Be The One (Avicii, Nicky Romero)",
  "Addicted To You (Avicii)",
  "Silhouettes (Avicii)",
  "Don't You Worry Child (Swedish House Mafia)",
  "Save The World (Swedish House Mafia)",
  "Miami 2 Ibiza (Swedish House Mafia, Tinie Tempah)",
  "Greyhound (Swedish House Mafia)",
  "Clarity (Zedd, Foxes)",
  "Stay The Night (Zedd, Hayley Williams)",
  "Spectrum (Zedd, Matthew Koma)",
  "I Want You To Know (Zedd, Selena Gomez)",
  "Beautiful Now (Zedd, Jon Bellion)",
  "The Middle (Zedd, Maren Morris, Grey)",
  "Stay (Zedd, Alessia Cara)",
  "Scared To Be Lonely (Martin Garrix, Dua Lipa)",
  "In The Name Of Love (Martin Garrix, Bebe Rexha)",
  "Animals (Martin Garrix)",
  "High On Life (Martin Garrix, Bonn)",
  "Ocean (Martin Garrix, Khalid)",
  "So Far Away (Martin Garrix, David Guetta, Jamie Scott, Romy Dya)",
  "There For You (Martin Garrix, Troye Sivan)",
  "Helicopter (Martin Garrix, Firebeatz)",
  "Boom (Tiesto, Sevenn)",
  "Red Lights (Tiesto)",
  "Jackie Chan (Tiesto, Dzeko, Preme, Post Malone)",
  "The Business (Tiesto)",
  "Wasted (Tiesto, Matthew Koma)",
  "Secrets (Tiesto, KSHMR, Vassy)",
  "Lethal Industry (Tiesto)",
  "Adagio For Strings (Tiesto)",
  "Boom Clap (Charli XCX)",
  "Break The Rules (Charli XCX)",
  "1999 (Charli XCX, Troye Sivan)",
  "Vroom Vroom (Charli XCX)",
  "Gone (Charli XCX, Christine and the Queens)",
  "Boys (Charli XCX)",
  "Beg For You (Charli XCX, Rina Sawayama)",
  "Used To Know Me (Charli XCX)",
  "Good Ones (Charli XCX)",
  "Unlock It (Charli XCX, Kim Petras, Jay Park)",
  "Claws (Charli XCX)",
  "Out Of My Head (Charli XCX, Tove Lo, ALMA)",
  "I Love It (Icona Pop, Charli XCX)",
  "All Night (Icona Pop)",
  "Emergency (Icona Pop)",
  "Girlfriend (Icona Pop)",
  "Ready For The Weekend (Icona Pop)",
  "We Got The World (Icona Pop)",
  "Superlove (Charli XCX)",
  "Electric Feel (MGMT)",
  "Kids (MGMT)",
  "Time To Pretend (MGMT)",
  "Little Dark Age (MGMT)",
  "Me and Michael (MGMT)",
  "The Less I Know The Better (Tame Impala)",
  "Let It Happen (Tame Impala)",
  "Eventually (Tame Impala)",
  "Feels Like We Only Go Backwards (Tame Impala)",
  "Elephant (Tame Impala)",
  "Borderline (Tame Impala)",
  "Reality In Motion (Tame Impala)",
  "New Person, Same Old Mistakes (Tame Impala)",
  "Lost In Yesterday (Tame Impala)",
  "Breathe Deeper (Tame Impala)",
  "Posthumous Forgiveness (Tame Impala)",
  "Losing It (FISHER)",
  "Your Love (Mark Knight)",
  "Turn Off the Lights (Chris Lake)",
  "Cola (CamelPhat & Elderbrook)",
  "Stimulation (Firebeatz)",
  "Deep Down (Alok, Ella Eyre)",
  "My High (Disclosure, Aminé, slowthai)",
  "Midnight (Lane 8)",
  "Piece of Your Heart (Meduza)",
  "Body Funk (Purple Disco Machine)",
  "Innerbloom (RÜFÜS DU SOL)",
  "I Wanna Know (Joe Stone)",
  "The Veldt (deadmau5)",
  "Promises (Calvin Harris, Sam Smith)",
  "Real Life (Duke Dumont, Gorgon City)",
  "All My Friends (Snakehips, Tinashe)",
  "Stay Forever (Whethan, STRFKR)",
  "Intoxicated (Martin Solveig, GTA)",
  "Pjanoo (Eric Prydz)",
  "One Kiss (Calvin Harris, Dua Lipa)",
  "Sun Is Shining (Axwell /\ Ingrosso)",
  "Jubel (Klingande)",
  "Omen (Disclosure, Sam Smith)",
  "Need U (100%) (Duke Dumont)",
  "Ocean Drive (Duke Dumont)",
  "Take Me Away (DJ S.K.T)",
  "Turn Me On (Riton, Oliver Heldens)",
  "Eyes Closed (Joe Goddard)",
  "Glue (Bicep)",
  "Electric Feel (Justice Remix)",
  "Move Your Body (Marshall Jefferson)",
  "Midnight Hour (Skrillex, Boys Noize)",
  "Love Tonight (Shouse)",
  "My Frequency (Tiesto, 7 Skies)",
  "House Arrest (Sofi Tukker, Gorgon City)",
  "Set U Free (Planet Funk)",
  "Rhythm of the Night (Corona)",
  "Right Here Right Now (Fatboy Slim)",
  "Head & Heart (Joel Corry, MNEK)",
  "Ferrari (James Hype, Miggy Dela Rosa)",
  "Jerusalema (Master KG)",
  "Uyang'khumbula (Sun-EL Musician)",
  "Akanamali (Sun-EL Musician)",
  "Traveller (Lemon & Herb)",
  "Ndiza (Da Capo)",
  "Yini (Caiiro)",
  "Abalele (Kabza De Small)",
  "Vula Mlomo (Musa Keys)",
  "Sondela (Venom x Shishiliza)",
  "Ke Star (Focalistic)",
  "Healer Ntliziyo Yam (Gaba Cannal)",
  "Thando Lwami (Black Motion)",
  "Your Voice (Caiiro Remix) (Black Coffee)",
  "Bayethe (Zakes Bantwini, Nomcebo Zikode)",
  "LaLaLa (Heavy-K, Nokwazi)",
  "Wamuhle (Drega, Sir Trill)",
  "Vula Vala (DJ Maphorisa & Kabza De Small)",
  "Thixo Onofefe (DJ Stokie)",
  "Nguwe (Afro Brotherz)",
  "Feel the Wave (Caiiro)",
  "African Child (Euphonik)",
  "As'phuze (Kabza De Small & MDU aka TRP)",
  "Lost (Da Capo Remix) (DJ Kent)",
  "House Africa Sessions (Vinny Da Vinci)",
  "Uyathandwa (DJ SK)",
  "Amadlozi (Samthing Soweto)",
  "Asambe (Heavy-K, Intaba Yase Dubai)",
  "Angisakufuni (Caiiro)",
  "Shwele (Thandi Draai)",
  "Zulu Spirit (Dacapo & Rancido)",
  "Ndawo Yami (DJ Merlon, Mondli Ngcobo)",
  "Siyathandana (Cassper Nyovest, Boohle)",
  "Emakhaya (Mobi Dixon, Berita)",
  "Yehla Moya (Echo Deep)",
  "Lalela (NuroGroove)",
  "African Woman (Karyendasoul, Zakes Bantwini)",
  "Wicked (Afro Warriors)",
  "The Journey (DJ Clock)",
  "Ubomi Abumanga (Sun-EL Musician, Msaki)",
  "Call Me (SculpturedMusic)",
  "Peace (Shimza)",
  "Thula (Enoo Napa Remix)",
  "Lento (Professor, Speedy)",
  "Amadoda (Black Motion)",
  "Kuyabanda (DJ Ganyani, Nomcebo)",
  "Zwakala (Lulo Café)",
  "Umoya (Black Motion)",
  "Amasiko (Lula Odiba)",
  "Bawo (SculpturedMusic)",
  "Ndikhokhele (DJ Cleo Remix)",
  "Midnight City (M83)",
  "Electric Feel (MGMT)",
  "Time Moves Slow (BADBADNOTGOOD, Samuel T. Herring)",
  "Nightcall (Kavinsky)",
  "Tadow (Masego, FKJ)",
  "Get You (Daniel Caesar, Kali Uchis)",
  "Can’t Take My Eyes Off You (Lauryn Hill)",
  "Weightless (Marconi Union)",
  "Slow Dancing in the Dark (Joji)",
  "Borderline (Tame Impala)",
  "Retrograde (James Blake)",
  "I Wanna Be Yours (Arctic Monkeys)",
  "A Moment Apart (ODESZA)",
  "On & On (Erykah Badu)",
  "Lose It (Oh Wonder)",
  "All Night (Chance the Rapper, Knox Fortune)",
  "Lover Is a Day (Cuco)",
  "Warm Winds (Syd, Isaiah Rashad)",
  "The Recipe (Kendrick Lamar, Dr. Dre)",
  "First Class (Jack Harlow)",
  "Location (Khalid)",
  "Best Part (Daniel Caesar, H.E.R.)",
  "Mystery Lady (Masego, Don Toliver)",
  "Glowed Up (Kaytranada, Anderson .Paak)",
  "Pretty Little Birds (SZA, Isaiah Rashad)",
  "Versace on the Floor (Bruno Mars)",
  "The Less I Know the Better (Tame Impala)",
  "Pink + White (Frank Ocean)",
  "Crew (GoldLink, Brent Faiyaz, Shy Glizzy)",
  "Cranes in the Sky (Solange)",
  "Feel No Ways (Drake)",
  "Garden (SZA)",
  "Summertime Magic (Childish Gambino)",
  "Nights (Frank Ocean)",
  "Biking (Frank Ocean, JAY-Z, Tyler, The Creator)",
  "Hard to Say Goodbye (Ekali, Illenium, Chloe Angelides)",
  "Stolen Dance (Milky Chance)",
  "La Di Da (Kayla Rae)",
  "River (Leon Bridges)",
  "You’re the One (Kaytranada, Syd)",
  "Still Woozy (Goodie Bag)",
  "Bloom (The Paper Kites)",
  "Ocean Eyes (Billie Eilish)",
  "Riverside (Agnes Obel)",
  "Heat Waves (Glass Animals)",
  "Coffee (Miguel)",
  "Sunflower (Post Malone, Swae Lee)",
  "Come Through (H.E.R., Chris Brown)",
  "Wicked Games (The Weeknd)",
  "Vibe (Cookiee Kawaii)"
];